apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  # Define the desired number of NGINX pods
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        # Use the official NGINX image
        image: nginx:latest
        ports:
        - containerPort: 80
        - containerPort: 443

        # --- RESOURCE SPECIFICATION ---
        resources:
          requests:
            cpu: "50m"    # Request 0.1 CPU core (100 millicores)
            memory: "64Mi" # Request 64 Mebibytes of RAM
          limits:
            cpu: "110m"     # Limit to 0.25 CPU core
            memory: "128Mi" # Limit to 128 Mebibytes of RAM

        # Simple health check to ensure the pod is ready to receive traffic
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        # nodeSelector: # <-- REPLACE THIS BLOCK
        #   team: devops
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: team
                operator: In
                values:
                - devops # Hard requirement: MUST run on a node labeled team: devops
